version: '3.7'
services:
  postgresql:
    image: bitnami/postgresql:12.3.0
    ports:
      - '5432:5432'
    volumes:
      - database:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
volumes:
  database:
